### ISSUE TITLE
support non-standard PKGEXT / compression other than xz

### ISSUE THREAD

**Issue by akobel** [misterdanb/makefontpkg#3]
Hi,

thanks for makefontpkg.

Unfortunately, `.pkg.tar.xz` is hardcoded for the package extension. Since xz can be fairly costly (in particular for AUR packages that only unpack a heavy pre-built `.deb` and repack), I disabled that and rely on my filesystem compression; hence, for me, `PKGEXT=.pkg.tar` in `/etc/makepkg.conf`. Which means that the package file in the tempdir has an unexpected name, is not found, and the properly built package is not copied over, and makefontpkg fails with

`[Errno 2] No such file or directory: '...-any.pkg.tar.xz'`

I can see two fixes: either set the environment `PKGEXT=.pkg.tar.xz` and `SRCEXT=.src.tar.xz` for the `makepkg` call that builds the package and potentially override the user's choice (i.e., force xz), or rely on `makepkg --packagelist` to deliver the name of the package that has been (or will be) built. Unfortunately, there seems to be no equivalent that gets you `SRCEXT`; the only way I see here is to read that value from `/etc/makepkg.conf`.

If you just happen to stumble across this as a user that sees the same error message, the workaround is to use `PKGEXT=.pkg.tar.xz makefontpkg` instead of just `makefontpkg`.

**Comment by misterdanb** [comment]
Has been fixed by pull request.
